agent {
    data_dir = "/opt/spire/data"
    log_level = "INFO"
    trust_domain = "agentauthlab.local"
    server_address = "spire-server"
    server_port = "8081"
    join_token = "d9e53393-e1b7-4688-b725-127ab5c5fad8"
    socket_path = "/tmp/spire-agent/public/api.sock"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {
        }
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {
        }
    }
}
