FROM python:3.12-slim
WORKDIR /app
RUN pip install spiffe spiffe-tls flask requests python-dotenv
COPY shared /app/shared
COPY topic-1-identity /app/topic-1-identity
WORKDIR /app/topic-1-identity
CMD ["python", "agent.py"]
